services:
  redis:
    image: redis:7-alpine
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pioner-network

volumes:
  redis-data:

networks:
  pioner-network:
    driver: bridge
